### ISSUE TITLE
`BottomDrawerFragment` has padding for horizontal

### ISSUE THREAD

**Issue by dolphpire-manager** [zeoflow/material-elements#100]
**Description:** `BottomDrawerFragment` has padding for horizontal

**Expected behavior:** It should be empty by default.

**Comment by TeodorHMX1** [comment]
Yes, indeed. I'll get down to it soon. 😁

**Comment by dolphpire-manager** [comment]
Cool! +1 for the nice work.

**Comment by TeodorHMX1** [comment]
Thanks, @dolphpire-manager
