### ISSUE TITLE
Material ViewPager

### ISSUE THREAD

**Issue by teogor** [zeoflow/material-elements#60]
A new feature of the material-elements would be the addition of the material viewpager

We also happily accept [pull requests](https://github.com/zeoflow/material-elements/pulls).

**Comment by TeodorHMX1** [comment]
What do you mean by 'material viewpager'?

**Comment by teogor** [comment]
A viewpager that is easy customizable such as background, ripple effects and all this stuff

**Comment by TeodorHMX1** [comment]
I'll begin the development
