### ISSUE TITLE
Invalid content for the local.properties

### ISSUE THREAD

**Issue by TeodorHMX1** [zeoflow/material-elements#61]
For some reasons, unwanted rows appear in the `local.properties` file.

To help us triage faster, please check to make sure you are using the [latest version](https://github.com/zeoflow/material-elements/releases) of the library.

We also happily accept [pull requests](https://github.com/zeoflow/material-elements/pulls).

**Comment by teogor** [comment]
I don't know why it happens. We should add the file to the `.gitignore`
